Q1.
- Train a decision tree model using the raw accelerometer data. Report the accuracy, precision, recall and confusion matrix of the model.

In [27]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

In [37]:
# Define file paths
axes = ["x", "y", "z"]
file_paths = {axis: f"data+scripts/human+activity+recognition+using+smartphones/UCI HAR Dataset/UCI HAR Dataset/train/Inertial Signals/total_acc_{axis}_train.txt" for axis in axes}

# Load data for each axis into a dictionary of DataFrames
dfs = {axis: pd.read_csv(file_paths[axis], header=None, delim_whitespace=True) for axis in axes}

# Compute the magnitude of acceleration
# Calculate sqrt(x^2 + y^2 + z^2) for each row
df_acc = pd.DataFrame(np.sqrt(dfs['x']**2 + dfs['y']**2 + dfs['z']**2))

# Optionally, save to a CSV file
df_acc.to_csv("combined_total_acceleration.csv", index=False, header=False)

# Load the combined acceleration magnitude data for training
df_train_acc = pd.read_csv("data+scripts/human+activity+recognition+using+smartphones/UCI HAR Dataset/__MACOSX/UCI HAR Dataset/train/Inertial Signals/combined_total_acceleration.csv", header=None)


C:\Users\SIDDHARTH\AppData\Local\Temp\ipykernel_12524\4027573769.py:6: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  dfs = {axis: pd.read_csv(file_paths[axis], header=None, delim_whitespace=True) for axis in axes}
C:\Users\SIDDHARTH\AppData\Local\Temp\ipykernel_12524\4027573769.py:6: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  dfs = {axis: pd.read_csv(file_paths[axis], header=None, delim_whitespace=True) for axis in axes}
C:\Users\SIDDHARTH\AppData\Local\Temp\ipykernel_12524\4027573769.py:6: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  dfs = {axis: pd.read_csv(file_paths[axis], header=None, delim_whitespace=True) for axis in axes}


In [ ]:
# df_acc

In [38]:
# Load the labels for training data
y_train = pd.read_csv("data+scripts/human+activity+recognition+using+smartphones/UCI HAR Dataset/UCI HAR Dataset/train/y_train.txt", header=None)

# Load the combined acceleration magnitude data for testing (repeat the magnitude calculation process for test data)
axes = ["x", "y", "z"]
file_paths_test = {axis: f"data+scripts/human+activity+recognition+using+smartphones/UCI HAR Dataset/UCI HAR Dataset/test/Inertial Signals/total_acc_{axis}_test.txt" for axis in axes}

# Load data for each axis into a dictionary of DataFrames for the test set
dfs_test = {axis: pd.read_csv(file_paths_test[axis], header=None, delim_whitespace=True) for axis in axes}

# Compute the magnitude of acceleration for the test set
df_test_acc = pd.DataFrame(np.sqrt(dfs_test['x']**2 + dfs_test['y']**2 + dfs_test['z']**2))

# Load the labels for the test data
y_test = pd.read_csv("data+scripts/human+activity+recognition+using+smartphones/UCI HAR Dataset/UCI HAR Dataset/test/y_test.txt", header=None)


C:\Users\SIDDHARTH\AppData\Local\Temp\ipykernel_12524\3391091943.py:9: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  dfs_test = {axis: pd.read_csv(file_paths_test[axis], header=None, delim_whitespace=True) for axis in axes}
C:\Users\SIDDHARTH\AppData\Local\Temp\ipykernel_12524\3391091943.py:9: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  dfs_test = {axis: pd.read_csv(file_paths_test[axis], header=None, delim_whitespace=True) for axis in axes}
C:\Users\SIDDHARTH\AppData\Local\Temp\ipykernel_12524\3391091943.py:9: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  dfs_test = {axis: pd.read_csv(file_paths_test[axis], header=None, delim_whitespace=True) for axis in axes}


In [39]:
# Train a Decision Tree model
model = DecisionTreeClassifier()
model.fit(df_train_acc, y_train)

# Predict the labels for the test set
y_pred = model.predict(df_test_acc)

In [40]:
# Calculate accuracy, precision, recall, and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)


Accuracy: 0.6263997285374957
Precision: 0.6295353025285968
Recall: 0.6263997285374957
Confusion Matrix:
[[352  86  46   3   5   4]
 [145 249  63   3   5   6]
 [ 54 114 247   0   2   3]
 [  1   0   0 241 137 112]
 [  4   1   0 116 393  18]
 [  2   4   0 160   7 364]]

Classification Report:
              precision    recall  f1-score   support

           1       0.63      0.71      0.67       496
           2       0.55      0.53      0.54       471
           3       0.69      0.59      0.64       420
           4       0.46      0.49      0.48       491
           5       0.72      0.74      0.73       532
           6       0.72      0.68      0.70       537

    accuracy                           0.63      2947
   macro avg       0.63      0.62      0.62      2947
weighted avg       0.63      0.63      0.63      2947



- Train a decision tree model using the features obtained by TSFEL. Report the accuracy, precision, recall and confusion matrix of the model.

In [6]:
import pandas as pd

# Reading the data from the text file into a pandas DataFrame
X_train = pd.read_csv(
    'data+scripts/human+activity+recognition+using+smartphones/UCI HAR Dataset/UCI HAR Dataset/train/X_train.txt',
    sep='\s+', # white space as delimiter
    header=None  # No header row in the file
)

# Display the first few rows of the DataFrame
print("X shape: ",X_train.shape)

y_train=pd.read_csv(
    'data+scripts/human+activity+recognition+using+smartphones/UCI HAR Dataset/UCI HAR Dataset/train/y_train.txt',
    header=None
)



print("y shape: ",y_train.shape)


X shape:  (7352, 561)
y shape:  (7352, 1)


In [7]:
X_test = pd.read_csv(
    'data+scripts/human+activity+recognition+using+smartphones/UCI HAR Dataset/UCI HAR Dataset/test/X_test.txt',
    sep='\s+', # white space as delimiter
    header=None  # No header row in the file
)

y_test=pd.read_csv(
    'data+scripts/human+activity+recognition+using+smartphones/UCI HAR Dataset/UCI HAR Dataset/test/y_test.txt',
    header=None
)

print("X test shape: ",X_test.shape)
print("y test shape: ",y_test.shape)

X test shape:  (2947, 561)
y test shape:  (2947, 1)


In [13]:
# import tsfel
# import pandas as pd

# # Retrieves a pre-defined feature configuration file to extract all available features
# cfg = tsfel.get_features_by_domain()

# # Extract features using parallel processing
# tsfel_train_x = tsfel.time_series_features_extractor(cfg, X_train, n_jobs=-1)
# tsfel_test_x = tsfel.time_series_features_extractor(cfg, X_test, n_jobs=-1)

# print(tsfel_train_x.shape)
# print(tsfel_test_x.shape)


In [ ]:
# import tsfel
# import pandas as pd
# from joblib import Parallel, delayed

# # Retrieves a pre-defined feature configuration file to extract all available features
# cfg = tsfel.get_features_by_domain()

# # Function to extract features for a single time series instance
# def extract_features_for_instance(row):
#     return tsfel.time_series_features_extractor(cfg, row)

# # Parallel processing: Extract features for each row in parallel
# tsfel_train_x = pd.concat(Parallel(n_jobs=-1)(delayed(extract_features_for_instance)(X_train.iloc[i, :]) for i in range(len(X_train))), ignore_index=True)
# tsfel_test_x = pd.concat(Parallel(n_jobs=-1)(delayed(extract_features_for_instance)(X_test.iloc[i, :]) for i in range(len(X_test))), ignore_index=True)

# print(tsfel_train_x.shape)
# print(tsfel_test_x.shape)


In [15]:
# Train the Decision Tree model on the extracted features
# clf_tsfel = DecisionTreeClassifier()
# clf_tsfel.fit(tsfel_train_x, y_train)

# # Predict using the test set
# y_pred_tsfel = clf_tsfel.predict(tsfel_test_x)



In [ ]:
# # Calculate metrics
# accuracy_tsfel = accuracy_score(y_test, y_pred_tsfel)
# precision_tsfel = precision_score(y_test, y_pred_tsfel, average='weighted')
# recall_tsfel = recall_score(y_test, y_pred_tsfel, average='weighted')
# conf_matrix_tsfel = confusion_matrix(y_test, y_pred_tsfel)

# # Report the results
# print("\nResults using TSFEL features:")
# print(f"Accuracy: {accuracy_tsfel}")
# print(f"Precision: {precision_tsfel}")
# print(f"Recall: {recall_tsfel}")
# print(f"Confusion Matrix:\n{conf_matrix_tsfel}")

In [41]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
import tsfel
import pandas as pd
from joblib import Parallel, delayed
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score



In [18]:
# Retrieves a pre-defined feature configuration file to extract all available features
cfg = tsfel.get_features_by_domain()

# Function to extract features for a single time series instance
def extract_features_for_instance(row):
    return tsfel.time_series_features_extractor(cfg, row)

# Parallel processing: Extract features for each row in parallel
tsfel_train_x = pd.concat(Parallel(n_jobs=-1)(delayed(extract_features_for_instance)(X_train.iloc[i, :]) for i in range(len(X_train))), ignore_index=True)
tsfel_test_x = pd.concat(Parallel(n_jobs=-1)(delayed(extract_features_for_instance)(X_test.iloc[i, :]) for i in range(len(X_test))), ignore_index=True)

# Combine original and TSFEL features
combined_train_x = pd.concat([X_train, tsfel_train_x], axis=1)
combined_test_x = pd.concat([X_test, tsfel_test_x], axis=1)

# Convert all column names to strings to avoid TypeError
combined_train_x.columns = combined_train_x.columns.astype(str)
combined_test_x.columns = combined_test_x.columns.astype(str)

# Train a Decision Tree model
model = DecisionTreeClassifier()
model.fit(combined_train_x, y_train)

# Predict and evaluate
y_pred = model.predict(combined_test_x)
accuracy = accuracy_score(y_test, y_pred)

print(f"Combined Features Accuracy: {accuracy}")


Combined Features Accuracy: 0.8184594502884289


In [20]:
# combined_train_x.shape

(7352, 950)

In [19]:
# Predict and evaluate
y_pred = model.predict(combined_test_x)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

# Print the results
print(f"Combined Features Accuracy: {accuracy}")
print(f"Combined Features Precision: {precision}")
print(f"Combined Features Recall: {recall}")
print("Confusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(class_report)

Combined Features Accuracy: 0.8184594502884289
Combined Features Precision: 0.8209495486889987
Combined Features Recall: 0.8184594502884289
Confusion Matrix:
[[373 107  16   0   0   0]
 [ 93 343  35   0   0   0]
 [ 30  58 332   0   0   0]
 [  0   0   0 382 109   0]
 [  0   0   0  87 445   0]
 [  0   0   0   0   0 537]]

Classification Report:
              precision    recall  f1-score   support

           1       0.75      0.75      0.75       496
           2       0.68      0.73      0.70       471
           3       0.87      0.79      0.83       420
           4       0.81      0.78      0.80       491
           5       0.80      0.84      0.82       532
           6       1.00      1.00      1.00       537

    accuracy                           0.82      2947
   macro avg       0.82      0.81      0.82      2947
weighted avg       0.82      0.82      0.82      2947



- Train a decision tree model using the features provided in the dataset. Report the accuracy, precision, recall and confusion matrix of the model.


In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

clf=DecisionTreeClassifier()
clf.fit(X_train,y_train)

DecisionTreeClassifier()

In [9]:
y_pred=clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Generate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the results
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"Confusion Matrix:\n{conf_matrix}")

Accuracy: 0.8612147947064812
Precision: 0.8614644777998965
Recall: 0.8612147947064812
Confusion Matrix:
[[444  29  23   0   0   0]
 [ 65 364  42   0   0   0]
 [ 17  47 356   0   0   0]
 [  0   0   0 379 112   0]
 [  0   0   0  74 458   0]
 [  0   0   0   0   0 537]]
